name: Build

on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - tensorplex-dev
      - tensorplex-staging
      - tensorplex-prod

jobs:
  build_ui:
    name: Build UI
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.3'

      - name: Cache node modules
        uses: actions/cache@v4.0.2
        with:
          path: |
            node_modules
            ~/.npm
          key: dojo-ui-node-modules
          restore-keys: |
            dojo-ui-node-modules

      - name: NPM Install
        run: npm install --force

      - name: Run Build
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/tensorplex-dev" ]]; then
            export NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL_DEV }}
            export NEXT_PUBLIC_GA_TAG=${{ vars.NEXT_PUBLIC_GA_TAG_DEV }}
          elif [[ "${{ github.ref }}" == "refs/heads/tensorplex-staging" ]]; then
            export NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL_STAGING }}
            export NEXT_PUBLIC_GA_TAG=${{ vars.NEXT_PUBLIC_GA_TAG_STAGING }}
          elif [[ "${{ github.ref }}" == "refs/heads/tensorplex-prod" ]]; then
            export NEXT_PUBLIC_BACKEND_URL=${{ vars.NEXT_PUBLIC_BACKEND_URL_PROD }}
            export NEXT_PUBLIC_GA_TAG=${{ vars.NEXT_PUBLIC_GA_TAG_PROD }}
          fi
          npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.3.5
        with:
          name: next_artifacts
          path: |
            .next

  build_image:
    name: Build Image
    uses: ./.github/workflows/docker_build.yaml
    permissions:
      contents: read
      packages: write
    needs:
      - build_ui
